# Generated by Django 5.0.4 on 2024-04-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='type',
            new_name='src',
        ),
    ]
